[theme]

# Primary accent for interactive elements
primaryColor = '#9DB5C0'

# Background color for the main content area
backgroundColor = '#E4E4E4'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#9DB5C0'

# Color used for almost all text
#textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
#font = "sans serif"


